### ISSUE TITLE
windows linux都不能使用

### ISSUE THREAD

**Issue by komomon** [praetorian-inc/fingerprintx#4]
编译成exe 或linux直接运行二进制文件都不能使用
![image](https://user-images.githubusercontent.com/52700174/193395132-233fdec9-7d62-4b1f-b8ac-558e2f48e556.png)
![image](https://user-images.githubusercontent.com/52700174/193395182-9aa490ba-acea-49d7-917b-07ab1261f1be.png)

**Comment by komomon** [comment]
环境 
![image](https://user-images.githubusercontent.com/52700174/193395199-2d63103c-a92e-4b7a-b1e6-bee4f5ecd5ef.png)
自己编译或使用release 都不能使用

**Comment by praetorian-thendrickson** [comment]
Hey @komomon thanks for bringing this to our attention. I think you're getting an error because the `-t` flag is specified twice and n the second image it looks like there is no port for the target. 

I updated the README and error message (https://github.com/praetorian-inc/fingerprintx/pull/5) so now the program will print out more descriptive errors when this happens and the `-v` flag is specified. Additionally the usage menu has more detail about what a valid target is.

With the updates I'm going to close this issue. Thanks for checking out the tool !
